# fly.toml app configuration file generated for billion-oak-dev on 2024-11-29T18:47:22-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'billion-oak-dev'
primary_region = 'hkg'
kill_signal = 'SIGTERM'

[build]

[deploy]
  release_command = '/app/bin/migrate'

[env]
  PHX_HOST = 'billion-oak-dev.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
